version: '3.8'

services:
  chatroom-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=flamekaiser
      - DB_NAME=chatroom
      - BREVO_API_KEY=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

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: flamekaiser
      MYSQL_DATABASE: chatroom
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pflamekaiser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
